.github/workflows/ci.yml
src/index.js

fix: copy the empty spec to temp folder before running

---

package-lock.json
package.json
src/index.js

feat: add spec stats to the GHA summary table

---

README.md

Added a sample Jenkins file to run cypress split

update README.md with sample jenkins file

---

.github/workflows/ci.yml
README.md
components/comp1.cy.js
components/comp2.cy.js
cypress.config.js
cypress/fixtures/example.json
cypress/support/commands.js
cypress/support/component-index.html
cypress/support/component.js
package-lock.json
package.json
vite.config.js

feat: support split component tests

---

.github/workflows/ci.yml
README.md
package-lock.json
package.json
src/index.js
src/utils.js

feat: summary toggle flag

---

README.md
package.json
src/types.d.ts

feat: add ts file with types

---

src/index.js

fix: grab both spec duration fields

---

.github/workflows/ci.yml
README.md
src/index.js

feat: add index starting with 1 support

---

README.md
src/index.js

feat: write timings into a file if it does not exist yet

---

README.md
src/index.js
src/timings.js
timings.json

feat: merge and save the updated timings file

---

README.md
package-lock.json
package.json
src/index.js

feat: ignore timing for failed specs

---

.github/workflows/ci.yml
.gitignore
bin/merge.js
examples/split-times/a/timings.json
examples/split-times/b/timings.json
package-lock.json
package.json
src/timings.js

feat: add merge timings bin utility

---

README.md

Update Correct cypress config code 
- For cypress below version 10

README FIX: Correct Cypress config code

---

src/index.js
src/timings.js
src/utils.js

feat: print spec estimates

---

src/index.js

fix: round durations to ms

---

src/timings.js

fix: polyfill structuredClone

---

cypress/e2e/merge-timings.cy.js
src/timings.js

fix: use average of durations when merging

---

README.md
src/index.js

fix: use env.splitOutputFile variable name

---

.github/workflows/ci.yml
README.md
bin/preview.js
package.json
src/index.js
src/parse-inputs.js
src/utils.js

feat: adding preview command

---

src/parse-inputs.js

Hey! This is a small add to support [Buildkite](https://buildkite.com/). Based on the [environment variables](https://buildkite.com/docs/pipelines/environment-variables), and successfully tested on one of my projects.

feat: add buildkite support

---

.github/workflows/ci.yml
README.md
package.json
src/parse-inputs.js

The wildcards seem to work for me
#231

test SPEC wildcards

---

src/index.js

feat: add chunk status to the heading

---

README.md
cypress.config.js
src/index.js
src/utils.js

feat: custom specs callback

---

.github/workflows/ci.yml
package-lock.json
package.json

fix: bump dependencies to satisfy the audit
